services:
  redis:
    image: redis:6
    ports:
      - "6379:6379"
    environment:
      - REDIS_URL=redis://redis:6379
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    environment:
      - MONGO_URL=mongodb://mongo:27017/scraperdb
  app:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mongo
